name: Deploy Admin Frontend

on:
  push:
    branches:
      - main
      - qa
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables
        id: env-vars
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "STAGE=prod" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ secrets.API_URL_PROD }}" >> $GITHUB_ENV
            echo "VITE_USER_POOL_ID=${{ secrets.USER_POOL_ID_PROD }}" >> $GITHUB_ENV
            echo "VITE_APP_CLIENT_ID=${{ secrets.APP_CLIENT_ID_PROD }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/qa' ]]; then
            echo "STAGE=qa" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ secrets.API_URL_QA }}" >> $GITHUB_ENV
            echo "VITE_USER_POOL_ID=${{ secrets.USER_POOL_ID_QA }}" >> $GITHUB_ENV
            echo "VITE_APP_CLIENT_ID=${{ secrets.APP_CLIENT_ID_QA }}" >> $GITHUB_ENV
          else
            echo "STAGE=dev" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ secrets.API_URL_DEV }}" >> $GITHUB_ENV
            echo "VITE_USER_POOL_ID=${{ secrets.USER_POOL_ID_DEV }}" >> $GITHUB_ENV
            echo "VITE_APP_CLIENT_ID=${{ secrets.APP_CLIENT_ID_DEV }}" >> $GITHUB_ENV
          fi

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ env.VITE_API_URL }}
          VITE_USER_POOL_ID: ${{ env.VITE_USER_POOL_ID }}
          VITE_APP_CLIENT_ID: ${{ env.VITE_APP_CLIENT_ID }}

      - name: Install Serverless and Plugins
        run: npm install -g serverless@3.35.2 && npm install

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: sls deploy --stage ${{ env.STAGE }}
